# Docs for the Azure Web Apps Deploy action: https://github.com/Azure/webapps-deploy
# More GitHub Actions for Azure: https://github.com/Azure/actions

name: Build and deploy container app to Azure Web App - webappngahadjo

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: 'ubuntu-latest'

    steps:
    - uses: actions/checkout@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1

    - name: Log in to registry
      uses: docker/login-action@v1
      with:
        registry: https://index.docker.io/v1/
        username: ${{ secrets.AzureAppService_ContainerUsername_ca47d7f7b8d845dc8ceb432327d6f414 }}
        password: ${{ secrets.AzureAppService_ContainerPassword_8af5ad9d37c3454197c20abb586da849 }}

    - name: Build and push container image to registry
      uses: docker/build-push-action@v2
      with:
        push: true
        tags: index.docker.io/${{ secrets.AzureAppService_ContainerUsername_ca47d7f7b8d845dc8ceb432327d6f414 }}/v1:${{ github.sha }}
        file: ./Dockerfile

  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: 'production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}

    steps:
    - name: Deploy to Azure Web App
      id: deploy-to-webapp
      uses: azure/webapps-deploy@v2
      with:
        app-name: 'webappngahadjo'
        slot-name: 'production'
        publish-profile: ${{ secrets.AzureAppService_PublishProfile_6402f0b913174ba2acafd8b9891992a8 }}
        images: 'index.docker.io/${{ secrets.AzureAppService_ContainerUsername_ca47d7f7b8d845dc8ceb432327d6f414 }}/v1:${{ github.sha }}'